[package]
name = "imagescreen"
version = "0.1.0"
edition = "2021"

[dependencies]
druid = "0.8.3"
image = "0.25.1"
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
tempfile = "3.10.1"
tokio = {version = "1.38.0", features = ["full"] }
